services:
  postgres:
    image: 'postgres:latest'
    restart: always
    environment:
      - 'POSTGRES_DB=skiStation'
      - 'POSTGRES_PASSWORD=root'
    ports:
      - '54321:5432'
    volumes:
      - './init.sql:/docker-entrypoint-initdb.d/init.sql'
