services:
  postgres:
    image: 'plgr229/tab_ski-station_postgres:latest'
    restart: always
    environment:
      - 'POSTGRES_DB=skiStation'
      - 'POSTGRES_PASSWORD=root'
    networks:
      - skistation-network

  ski-station:
    image: 'plgr229/tab_ski-station_backend:latest'
    restart: always
    depends_on:
      - postgres
    environment:
      - 'SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/skiStation'
      - 'SPRING_DATASOURCE_USERNAME=postgres'
      - 'SPRING_DATASOURCE_PASSWORD=root'
    ports:
      - '8080:8080'
    networks:
      - skistation-network
      - skistation-exposed

  ski-station-front:
    image: 'plgr229/ski-station_frontend:latest'
    restart: always
    depends_on:
      - ski-station
    ports:
      - '4321:4321'
    networks:
      - skistation-exposed

networks:
  skistation-network:
    driver: bridge
    internal: true
  skistation-exposed:
    driver: bridge
